### ISSUE TITLE
Free Company tracking

### ISSUE THREAD

**Issue by JamesDonnelly** [ApkalluFalls/apkallufalls.com#6]
Investigate the ability to track entire Free Companies.

- [ ] Investigate whether it's possible to pull entire Free Companies via the XIVDB API.
- [ ] Prototype how this could be implemented onto Apkallu Falls.
- [ ] Perform necessary API upgrades.
- [ ] Display stats for the entire Free Company.
- [ ] Implement a filterable table revealing which characters have which minions and mounts (as suggested by Bruno Ferreira on Discord).
- [ ] Investigate how this could be used to give Patreon supporters perks (like offering the ability to have a list of supporting Free Companies as well as supporting characters).

**Comment by JamesDonnelly** [comment]
Version 3 of XIVDB's API will include a lot more support for Free Companies than their V2 API currently does. Because of this, development right now is in very much of an as-it-becomes-ready state. Free Company searching is only supported through XIVSync, which isn't ideal and certainly won't be used in the final version. Likewise, extracting data on characters belonging to a certain Free Company is currently not possible on either the V2 API or XIVSync.
